### ISSUE TITLE
可以沟通一下wookteam的问题吗

### ISSUE THREAD

**Issue by ALuciferDK** [kuaifan/sdos#1]
我这边使用遇到了问题，但是您在gitee上留下的联系方式，我联系不上，然后在github上找到您，想和您沟通一下。

**Comment by kuaifan** [comment]
周末没看那个账号

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: coffeemilk ***@***.***&gt;
发送时间: 2021年8月14日 16:55
收件人: kuaifan/sdos ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[kuaifan/sdos] 可以沟通一下wookteam的问题吗 (#1)





 
我这边使用遇到了问题，但是您在gitee上留下的联系方式，我联系不上，然后在github上找到您，想和您沟通一下。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ALuciferDK** [comment]
那可以给个联系方式，沟通一下吗，什么联系方式都行，邮件沟通也可以

**Comment by kuaifan** [comment]
gitee上留下的联系方式就可以啊，我已经添加好友了

**Comment by ALuciferDK** [comment]
多谢
